version: '3'

volumes:
  backend-static:

services:
  redis:
    image: "redis:alpine"
  neo_bundle:
    restart: always
    build: .
    image: neo_bundle_backend
    env_file: .env
    ports:
      - "8002:8006"
    command: gunicorn -w 10 neo_bundle.wsgi:application -b :8006 -t 9999
    volumes:
      - .:/neo_bundle
      - backend-static:/neo_bundle/static
    depends_on:
      - redis
  celery:
    build: .
    container_name: neo_bundle_celery_worker
    command: celery worker -A neo_bundle --loglevel=debug --concurrency=4
    volumes:
      - .:/neo_bundle
    depends_on:
      - redis
      - neo_bundle
  celery-beat:
    build: .
    container_name: neo_bundle_celery_beat
    environment:
        CELERY_BROKER_URL: 'redis://redis:6379'
    command: celery -A neo_bundle beat --loglevel=debug --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/neo_bundle
    depends_on:
      - redis
      - neo_bundle

  nginx:
    restart: always
    build: ./nginx/
    image: neo_bundle_backend_nginx
    ports:
      - "8084:8084"
    volumes:
      - backend-static:/var/www/neo_bundle/static
    depends_on:
      - neo_bundle
